platform :ios, '9.0'

target 'test' do
  use_frameworks!

  pod 'Masonry'
  #pod 'AFNetworking'
  #pod 'SDWebImage'
  #pod 'MJRefresh'
  #pod 'MJExtension'
  #pod 'SVProgressHUD'
  #pod 'IQKeyboardManager'
  #pod 'HXPhotoPicker'
  #pod 'ReactiveObjC'

end
